import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.scss';
import { Providers } from './providers';
import styles from './dashboard.module.scss';
import { Header, Sidebar } from '@/components/layout';

const inter = Inter({
  subsets: ['latin'],
  variable: '--font-inter',
  display: 'swap',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja" className={inter.variable}>
      <body className={inter.className}>
        <Providers>
          <div className={styles.app}>
            <Header />
            <main className={styles.main}>
              <Sidebar />
              <div className={styles.container}>{children}</div>
            </main>
          </div>
        </Providers>
      </body>
    </html>
  );
}
